#!/usr/bin/env zsh

# Generated by crompt v0.1.0
# Script: example v0.0.1
# Authors: Your Name <your_name@mail.com>

set -e

# 全局变量
SCRIPT_NAME="example"
SCRIPT_VERSION="0.0.1"

# 颜色定义
COLOR_RESET="\033[0m"
COLOR_RED="\033[31m"
COLOR_GREEN="\033[32m"
COLOR_YELLOW="\033[33m"

# 错误处理函数
error() {
    echo -e "${COLOR_RED}错误: $1${COLOR_RESET}" >&2
    exit 1
}

# 显示帮助信息
show_help() {
    cat << EOF
$SCRIPT_NAME $SCRIPT_VERSION

使用方法:
    $SCRIPT_NAME <COMMAND> [OPTIONS]

命令:
    greet       向用户打招呼
    config      配置管理
    help        显示帮助信息

选项:
    -h, --help       显示帮助信息
    -v, --version    显示版本信息

使用 '$SCRIPT_NAME <COMMAND> --help' 查看特定命令的帮助信息
EOF
}

# 显示版本信息
show_version() {
    echo "$SCRIPT_NAME $SCRIPT_VERSION"
    echo "Authors: Your Name <your_name@mail.com>"
}

# greet 命令帮助
show_greet_help() {
    cat << EOF
$SCRIPT_NAME-greet
向用户打招呼

使用方法:
    $SCRIPT_NAME greet [OPTIONS]
    $SCRIPT_NAME greet <SUBCOMMAND>

选项:
    -n, --name <NAME>     要打招呼的人的名字 [必需]
    -t, --times <TIMES>   重复打招呼的次数 [默认: 1]
    -l, --loud            使用大写字母
    -h, --help            显示帮助信息

子命令:
    morning    早上好的特殊问候
EOF
}

# greet morning 子命令帮助
show_greet_morning_help() {
    cat << EOF
$SCRIPT_NAME-greet-morning
早上好的特殊问候

使用方法:
    $SCRIPT_NAME greet morning [OPTIONS]

选项:
    -n, --name <NAME>    要打招呼的人的名字 [必需]
    -h, --help           显示帮助信息
EOF
}

# config 命令帮助
show_config_help() {
    cat << EOF
$SCRIPT_NAME-config
配置管理

使用方法:
    $SCRIPT_NAME config <SUBCOMMAND>

子命令:
    set     设置配置项
    get     获取配置项
EOF
}

# config set 子命令帮助
show_config_set_help() {
    cat << EOF
$SCRIPT_NAME-config-set
设置配置项

使用方法:
    $SCRIPT_NAME config set <KEY> <VALUE>

参数:
    <KEY>      配置项的键
    <VALUE>    配置项的值

选项:
    -h, --help    显示帮助信息
EOF
}

# config get 子命令帮助
show_config_get_help() {
    cat << EOF
$SCRIPT_NAME-config-get
获取配置项

使用方法:
    $SCRIPT_NAME config get <KEY>

参数:
    <KEY>    配置项的键

选项:
    -h, --help    显示帮助信息
EOF
}

###########################################
# 用户实现区域 - greet 命令
###########################################
cmd_greet() {
    local name=""
    local times=1
    local loud=false

    # 参数解析
    while [[ $# -gt 0 ]]; do
        case $1 in
            -n|--name)
                name="$2"
                shift 2
                ;;
            -t|--times)
                times="$2"
                shift 2
                ;;
            -l|--loud)
                loud=true
                shift
                ;;
            -h|--help)
                show_greet_help
                exit 0
                ;;
            morning)
                shift
                cmd_greet_morning "$@"
                exit 0
                ;;
            *)
                error "未知参数: $1\n使用 '$SCRIPT_NAME greet --help' 查看帮助"
                ;;
        esac
    done

    # 参数验证
    [[ -z "$name" ]] && error "缺少必需参数: --name"

    # TODO: 在这里实现你的逻辑
    echo "TODO: 实现 greet 命令"
    echo "  name=$name"
    echo "  times=$times"
    echo "  loud=$loud"
}

###########################################
# 用户实现区域 - greet morning 子命令
###########################################
cmd_greet_morning() {
    local name=""

    # 参数解析
    while [[ $# -gt 0 ]]; do
        case $1 in
            -n|--name)
                name="$2"
                shift 2
                ;;
            -h|--help)
                show_greet_morning_help
                exit 0
                ;;
            *)
                error "未知参数: $1\n使用 '$SCRIPT_NAME greet morning --help' 查看帮助"
                ;;
        esac
    done

    # 参数验证
    [[ -z "$name" ]] && error "缺少必需参数: --name"

    # TODO: 在这里实现你的逻辑
    echo "TODO: 实现 greet morning 子命令"
    echo "  name=$name"
}

###########################################
# 用户实现区域 - config set 子命令
###########################################
cmd_config_set() {
    local key=""
    local value=""
    local positional_args=()

    # 参数解析
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_config_set_help
                exit 0
                ;;
            -*)
                error "未知选项: $1\n使用 '$SCRIPT_NAME config set --help' 查看帮助"
                ;;
            *)
                positional_args+=("$1")
                shift
                ;;
        esac
    done

    # 位置参数验证
    [[ ${#positional_args[@]} -lt 2 ]] && error "缺少必需的位置参数\n使用 '$SCRIPT_NAME config set --help' 查看帮助"

    key="${positional_args[0]}"
    value="${positional_args[1]}"

    # TODO: 在这里实现你的逻辑
    echo "TODO: 实现 config set 子命令"
    echo "  key=$key"
    echo "  value=$value"
}

###########################################
# 用户实现区域 - config get 子命令
###########################################
cmd_config_get() {
    local key=""
    local positional_args=()

    # 参数解析
    while [[ $# -gt 0 ]]; do
        case $1 in
            -h|--help)
                show_config_get_help
                exit 0
                ;;
            -*)
                error "未知选项: $1\n使用 '$SCRIPT_NAME config get --help' 查看帮助"
                ;;
            *)
                positional_args+=("$1")
                shift
                ;;
        esac
    done

    # 位置参数验证
    [[ ${#positional_args[@]} -lt 1 ]] && error "缺少必需的位置参数\n使用 '$SCRIPT_NAME config get --help' 查看帮助"

    key="${positional_args[0]}"

    # TODO: 在这里实现你的逻辑
    echo "TODO: 实现 config get 子命令"
    echo "  key=$key"
}

###########################################
# 用户实现区域 - config 命令
###########################################
cmd_config() {
    [[ $# -eq 0 ]] && { show_config_help; exit 1; }

    local subcommand="$1"
    shift

    case "$subcommand" in
        set)
            cmd_config_set "$@"
            ;;
        get)
            cmd_config_get "$@"
            ;;
        -h|--help|help)
            show_config_help
            exit 0
            ;;
        *)
            error "未知子命令: $subcommand\n使用 '$SCRIPT_NAME config --help' 查看帮助"
            ;;
    esac
}

###########################################
# 主函数
###########################################
main() {
    # 没有参数时显示帮助
    [[ $# -eq 0 ]] && { show_help; exit 0; }

    # 解析全局选项
    case "$1" in
        -h|--help|help)
            show_help
            exit 0
            ;;
        -v|--version)
            show_version
            exit 0
            ;;
    esac

    # 解析命令
    local command="$1"
    shift

    case "$command" in
        greet)
            cmd_greet "$@"
            ;;
        config)
            cmd_config "$@"
            ;;
        *)
            error "未知命令: $command\n使用 '$SCRIPT_NAME --help' 查看帮助"
            ;;
    esac
}

# 执行主函数
main "$@"

